### ISSUE TITLE
Crash on connecting to server

### ISSUE THREAD

**Issue by Brother-Blue** [SSKirillSS/relics#100]
I'm not entirely sure this isn't modpack related, but currently a player on my server immediately crashes when attempting to join.

Modpack: TNP Limitless 6 1.19.2

```txt
[05.06 08:47:10] [Server] Caused byjava.lang.NullPointerException: Cannot invoke "it.hurts.sskirillss.relics.items.relics.base.data.leveling.RelicAbilityData.getAbilities()" because the return value of "it.hurts.sskirillss.relics.items.relics.base.utils.AbilityUtils.getRelicAbilityData(net.minecraft.world.item.Item)" is null
[05.06 08:47:10] [Server] 	at it.hurts.sskirillss.relics.items.relics.base.RelicItem.m_6883_(RelicItem.java:108) ~[relics-1.19.2-0.4.6.jar%231025!/:1.19.2-0.4.{re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
[05.06 08:47:10] [Server] 	at net.minecraft.world.item.ItemStack.m_41666_(ItemStack.java:508) ~[server-1.19.2-20220805.130853-srg.jar%231171!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:kubejs-common.mixins.json:ItemStackMixin,pl:mixin:APP:mixins.hammerlib.json:ItemStackMixin,pl:mixin:APP:apotheosis.mixins.json:ItemStackMixin,pl:mixin:APP:tombstone.mixins.json:ItemStackMixin,pl:mixin:APP:placebo.mixins.json:ItemStackMixin,pl:mixin:APP:creatures-and-beasts.mixins.json:MixinItemStack,pl:mixin:APP:elementalcraft.mixins.json:MixinItemStack,pl:mixin:APP:canary.mixins.json:block.hopper.ItemStackMixin,pl:mixin:APP:canary.mixins.json:item.ItemStackMixin,pl:mixin:APP:relics.mixins.json:MixinItemStack,pl:mixin:APP:itemfilters-common.mixins.json:ItemStackMixin,pl:mixin:APP:quark.mixins.json:ItemStackMixin,pl:mixin:APP:enigmaticlegacy.mixins.json:MixinItemStack,pl:mixin:A}
[05.06 08:47:10] [Server] 	at net.minecraft.world.entity.player.Inventory.m_36068_(Inventory.java:228) ~[server-1.19.2-20220805.130853-srg.jar%231171!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dankstorage.mixins.json:PlayerInventoryMixin,pl:mixin:APP:moonlight-common.mixins.json:InventoryMixin,pl:mixin:A}
[05.06 08:47:10] [Server] 	at net.minecraft.world.entity.player.Player.m_8107_(Player.java:499) ~[server-1.19.2-20220805.130853-srg.jar%231171!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:apotheosis.mixins.json:PlayerMixin,pl:mixin:APP:darkutils.mixins.json:MixinPlayer,pl:mixin:APP:darkutils.mixins.json:AccessorPlayer,pl:mixin:APP:supplementaries.mixins.json:PlayerProjectileMixin,pl:mixin:APP:botania_xplat.mixins.json:PlayerMixin,pl:mixin:APP:tombstone.mixins.json:PlayerMixin,pl:mixin:APP:the_bumblezone.mixins.json:items.HoneyShieldPlayerMixin,pl:mixin:APP:the_bumblezone.mixins.json:items.PlayerDamageShieldInvoker,pl:mixin:APP:personality.mixins.json:PlayerMixin,pl:mixin:APP:ad_astra-common.mixins.json:PlayerMixin,pl:mixin:APP:elementalcraft.mixins.json:MixinPlayer,pl:mixin:APP:friendsandfoes-common.mixins.json:PlayerEntityMixin,pl:mixin:APP:AdditionalAdditions.mixins.json:PlayerMixin,pl:mixin:APP:enderzoology.common.mixins.json:PlayerMixin,pl:mixin:APP:ars_nouveau.mixins.json:elytra.ElytraPlayerMixin,pl:mixin:APP:nochatreports.mixins.json:server.MixinPlayer,pl:mixin:APP:canary.mixins.json:calc.if_else.entity.handle_entity_event.player.PlayerMixin,pl:mixin:APP:canary.mixins.json:calc.if_else.player_slot.PlayerMixin,pl:mixin:APP:byg.mixins.json:common.entity.MixinPlayer,pl:mixin:APP:blue_skies.mixins.json:PlayerEntityMixin,pl:mixin:APP:allurement.mixins.json:PlayerMixin,pl:mixin:APP:expandedstorage-common.mixins.json:SpectatorEntityInventoryViewingFix,pl:mixin:APP:comforts.mixins.json:AccessorPlayer,pl:mixin:APP:diet.mixins.json:DietMixinPlayer,pl:mixin:APP:universalenchants.forge.mixins.json:ForgePlayerMixin,pl:mixin:APP:expandability-common.mixins.json:swimming.PlayerMixin,pl:mixin:APP:enigmaticlegacy.mixins.json:MixinPlayer,pl:mixin:APP:kubejs-common.mixins.json:PlayerMixin,pl:mixin:A}
[05.06 08:47:10] [Server] 	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2291) ~[server-1.19.2-20220805.130853-srg.jar%231171!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:LivingEntityMixin,pl:mixin:APP:apotheosis.mixins.json:MHFMixinLivingEntity,pl:mixin:APP:apotheosis.mixins.json:LivingEntityMixin,pl:mixin:APP:apotheosis.mixins.json:LivingEntityInvoker,pl:mixin:APP:supplementaries-common.mixins.json:LivingEntityMixin,pl:mixin:APP:botania_xplat.mixins.json:LivingEntityAccessor,pl:mixin:APP:snowpig.mixins.json:SPLivingEntityMixin,pl:mixin:APP:tombstone.mixins.json:LivingEntityMixin,pl:mixin:APP:the_bumblezone.mixins.json:entities.LivingEntityAccessor,pl:mixin:APP:the_bumblezone.mixins.json:entities.LivingEntityMixin,pl:mixin:APP:caelus.mixins.json:MixinLivingEntity,pl:mixin:APP:oreberriesreplanted.mixins.json:LivingEntityAccessor,pl:mixin:APP:personality.mixins.json:LivingEntityMixin,pl:mixin:APP:ad_astra-common.mixins.json:LivingEntityMixin,pl:mixin:APP:ad_astra-common.mixins.json:gravity.LivingEntityGravityMixin,pl:mixin:APP:bookshelf.common.mixins.json:entity.AccessorLivingEntity,pl:mixin:APP:bookshelf.common.mixins.json:entity.MixinLivingEntity,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:spirit.common.mixins.json:LivingEntityMixin,pl:mixin:APP:elementalcraft.mixins.json:MixinLivingEntity,pl:mixin:APP:AdditionalAdditions.mixins.json:LivingEntityMixin,pl:mixin:APP:saturn.mixins.json:ai.brain.clear_memories.LivingEntityMixin,pl:mixin:APP:maxhealthfix.common.mixins.json:MixinLivingEntity,pl:mixin:APP:mixins.shetiphiancore.json:SPC_ThinBlockHandler$_LivingEntity,pl:mixin:APP:curios.mixins.json:MixinLivingEntity,pl:mixin:APP:ars_nouveau.mixins.json:elytra.MixinLivingEntity,pl:mixin:APP:ars_nouveau.mixins.json:perks.PerkLivingEntity,pl:mixin:APP:ecologics-common.mixins.json:LivingEntityMixin,pl:mixin:APP:earthmobsmod.mixins.json:LivingEntityMixin,pl:mixin:APP:canary.mixins.json:alloc.enum_values.living_entity.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.fast_elytra_check.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.fast_hand_swing.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.fast_powder_snow_check.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.skip_equipment_change_check.LivingEntityMixin,pl:mixin:APP:blue_skies.mixins.json:LivingEntityMixin,pl:mixin:APP:netherportalfix.mixins.json:LivingEntityAccessor,pl:mixin:APP:relics.mixins.json:MixinLivingEntity,pl:mixin:APP:allurement.mixins.json:LivingEntityAccessor,pl:mixin:APP:allurement.mixins.json:LivingEntityMixin,pl:mixin:APP:voidtotem.mixins.json:LivingEntityMixin,pl:mixin:APP:betterdeserttemples.mixins.json:PharaohKilledMixin,pl:mixin:APP:hexplat.mixins.json:accessor.AccessorLivingEntity,pl:mixin:APP:snowyspirit-common.mixins.json:EntityMixin,pl:mixin:APP:mixins.fishofthieves.json:entity.MixinLivingEntity,pl:mixin:APP:rottencreatures-common.mixins.json:common.LivingEntityMixin,pl:mixin:APP:quark.mixins.json:accessor.AccessorLivingEntity,pl:mixin:APP:universalenchants.common.mixins.json:LivingEntityMixin,pl:mixin:APP:universalenchants.common.mixins.json:accessor.LivingEntityAccessor,pl:mixin:APP:expandability.mixins.json:swimming.LivingEntityMixin,pl:mixin:APP:expandability-common.mixins.json:swimming.LivingEntityMixin,pl:mixin:APP:scena.mixins.json:common.LivingEntityEquipmentSlotMixin,pl:mixin:APP:enigmaticlegacy.mixins.json:MixinLivingEntity,pl:mixin:APP:create.mixins.json:CustomItemUseEffectsMixin,pl:mixin:APP:create.mixins.json:accessor.LivingEntityAccessor,pl:mixin:A}
[05.06 08:47:10] [Server] 	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:243) ~[server-1.19.2-20220805.130853-srg.jar%231171!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:apotheosis.mixins.json:PlayerMixin,pl:mixin:APP:darkutils.mixins.json:MixinPlayer,pl:mixin:APP:darkutils.mixins.json:AccessorPlayer,pl:mixin:APP:supplementaries.mixins.json:PlayerProjectileMixin,pl:mixin:APP:botania_xplat.mixins.json:PlayerMixin,pl:mixin:APP:tombstone.mixins.json:PlayerMixin,pl:mixin:APP:the_bumblezone.mixins.json:items.HoneyShieldPlayerMixin,pl:mixin:APP:the_bumblezone.mixins.json:items.PlayerDamageShieldInvoker,pl:mixin:APP:personality.mixins.json:PlayerMixin,pl:mixin:APP:ad_astra-common.mixins.json:PlayerMixin,pl:mixin:APP:elementalcraft.mixins.json:MixinPlayer,pl:mixin:APP:friendsandfoes-common.mixins.json:PlayerEntityMixin,pl:mixin:APP:AdditionalAdditions.mixins.json:PlayerMixin,pl:mixin:APP:enderzoology.common.mixins.json:PlayerMixin,pl:mixin:APP:ars_nouveau.mixins.json:elytra.ElytraPlayerMixin,pl:mixin:APP:nochatreports.mixins.json:server.MixinPlayer,pl:mixin:APP:canary.mixins.json:calc.if_else.entity.handle_entity_event.player.PlayerMixin,pl:mixin:APP:canary.mixins.json:calc.if_else.player_slot.PlayerMixin,pl:mixin:APP:byg.mixins.json:common.entity.MixinPlayer,pl:mixin:APP:blue_skies.mixins.json:PlayerEntityMixin,pl:mixin:APP:allurement.mixins.json:PlayerMixin,pl:mixin:APP:expandedstorage-common.mixins.json:SpectatorEntityInventoryViewingFix,pl:mixin:APP:comforts.mixins.json:AccessorPlayer,pl:mixin:APP:diet.mixins.json:DietMixinPlayer,pl:mixin:APP:universalenchants.forge.mixins.json:ForgePlayerMixin,pl:mixin:APP:expandability-common.mixins.json:swimming.PlayerMixin,pl:mixin:APP:enigmaticlegacy.mixins.json:MixinPlayer,pl:mixin:APP:kubejs-common.mixins.json:PlayerMixin,pl:mixin:A}
[05.06 08:47:10] [Server] 	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:447) ~[server-1.19.2-20220805.130853-srg.jar%231171!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:uteamcore:ServerPlayer#initMenu,re:classloading,pl:accesstransformer:B,xf:fml:uteamcore:ServerPlayer#initMenu,pl:mixin:APP:kubejs-common.mixins.json:ServerPlayerMixin,pl:mixin:APP:yungsapi.mixins.json:ServerPlayerEntityTickMixin,pl:mixin:APP:botania_xplat.mixins.json:ServerPlayerMixin,pl:mixin:APP:the_bumblezone.mixins.json:entities.ServerPlayerMixin,pl:mixin:APP:mixins.pneumaticcraft.json:accessors.ServerPlayerAccess,pl:mixin:APP:ars_nouveau.mixins.json:camera.ANServerPlayerMixin,pl:mixin:APP:byg.mixins.json:common.entity.MixinServerPlayer,pl:mixin:APP:chunksending.mixins.json:ServerPlayerChunkSending,pl:mixin:APP:netherportalfix.mixins.json:ServerPlayerMixin,pl:mixin:APP:netherportalfix.mixins.json:ForgeServerPlayerMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerPlayerTickMixin,pl:mixin:APP:tombstone.mixins.json:ServerPlayerMixin,pl:mixin:A}
[05.06 08:47:10] [Server] 	... more
[05.06 08:47:10] [Server] [Server thread/WARN] [minecraft/ServerConnectionListener]: Failed to handle packet for -------------
[05.06 08:47:10] [Server] net.minecraft.ReportedExceptionTicking player
[05.06 08:47:10] [Server] 	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:510) ~[server-1.19.2-20220805.130853-srg.jar%231171!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:uteamcore:ServerPlayer#initMenu,re:classloading,pl:accesstransformer:B,xf:fml:uteamcore:ServerPlayer#initMenu,pl:mixin:APP:kubejs-common.mixins.json:ServerPlayerMixin,pl:mixin:APP:yungsapi.mixins.json:ServerPlayerEntityTickMixin,pl:mixin:APP:botania_xplat.mixins.json:ServerPlayerMixin,pl:mixin:APP:the_bumblezone.mixins.json:entities.ServerPlayerMixin,pl:mixin:APP:mixins.pneumaticcraft.json:accessors.ServerPlayerAccess,pl:mixin:APP:ars_nouveau.mixins.json:camera.ANServerPlayerMixin,pl:mixin:APP:byg.mixins.json:common.entity.MixinServerPlayer,pl:mixin:APP:chunksending.mixins.json:ServerPlayerChunkSending,pl:mixin:APP:netherportalfix.mixins.json:ServerPlayerMixin,pl:mixin:APP:netherportalfix.mixins.json:ForgeServerPlayerMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerPlayerTickMixin,pl:mixin:APP:tombstone.mixins.json:ServerPlayerMixin,pl:mixin:A}
[05.06 08:47:10] [Server] 	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:264) ~[server-1.19.2-20220805.130853-srg.jar%231171!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
[05.06 08:47:10] [Server] 	at net.minecraft.network.Connection.m_129483_(Connection.java:248) ~[server-1.19.2-20220805.130853-srg.jar%231171!/:?] {re:mixin,re:classloading,pl:mixin:APP:connectivity.mixins.json:ConnectionErrorMixin,pl:mixin:APP:connectivity.mixins.json:NetworkManagerMixin,pl:mixin:A}
[05.06 08:47:10] [Server] 	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[server-1.19.2-20220805.130853-srg.jar%231171!/:?] {re:classloading}
[05.06 08:47:10] [Server] 	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:880) ~[server-1.19.2-20220805.130853-srg.jar%231171!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:A}
[05.06 08:47:10] [Server] 	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%231171!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:nochatreports.mixins.json:server.MixinDedicatedServer,pl:mixin:APP:blueprint.mixins.json:DedicatedServerMixin,pl:mixin:APP:tombstone.mixins.json:DedicatedServerMixin,pl:mixin:A}
[05.06 08:47:10] [Server] 	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%231171!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:A}
[05.06 08:47:10] [Server] 	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%231171!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:A}
[05.06 08:47:10] [Server] 	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%231171!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:A}
[05.06 08:47:10] [Server] 	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}
```

**Comment by SSKirillSS** [comment]
You have a Scarab Talisman (or other unobtainable relic). This item is creative-debug only, and it shouldn't be accessible from the survival game. It's a modpack issue, since it gives you these items. You need to manually remove it from player's data via NBT-Editor. You also may ask modpack author to remove this item from a lootbags or something.

**Comment by SSKirillSS** [comment]
All these items will be removed from the game in the next update.
