### ISSUE TITLE
NullPointerException console/log spam(?)

### ISSUE THREAD

**Issue by SubordinalBlue** [SSKirillSS/relics#169]
Excerpt from Craftoria official server:

```
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.Entity.level()" because "entity" is null
        at TRANSFORMER/relics@0.9.0.2/it.hurts.sskirillss.relics.utils.data.WorldPosition.<init>(WorldPosition.java:20) ~[relics-1.21-0.9.0.2.jar%23629!/:1.21-0.9.0.2] {re:classloading}
        at TRANSFORMER/rarcompat@0.1.5/it.hurts.octostudios.rarcompat.network.packets.PacketCreateZone.lambda$handle$0(PacketCreateZone.java:48) ~[rarcompat-1.21-0.1.5.jar%23624!/:1.21-0.1.5] {re:classloading}
        at TRANSFORMER/neoforge@21.1.56/net.neoforged.neoforge.network.handling.ServerPayloadContext.enqueueWork(ServerPayloadContext.java:32) ~[neoforge-21.1.56-universal.jar%23401!/:?] {re:classloading}
        at TRANSFORMER/rarcompat@0.1.5/it.hurts.octostudios.rarcompat.network.packets.PacketCreateZone.handle(PacketCreateZone.java:42) ~[rarcompat-1.21-0.1.5.jar%23624!/:1.21-0.1.5] {re:classloading}
        at TRANSFORMER/neoforge@21.1.56/net.neoforged.neoforge.network.handling.MainThreadPayloadHandler.lambda$handle$0(MainThreadPayloadHandler.java:16) ~[neoforge-21.1.56-universal.jar%23401!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:60) ~[server-1.21.1-20240808.144430-srg.jar%23400!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin from mod modernfix,pl:mixin:A}
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
        ... 13 more
```

**Comment by Temulla** [comment]
Hello. Fixed in version 0.2.1 and is already available for download:
https://www.curseforge.com/minecraft/mc-mods/rar-compat/files/5742337
