### ISSUE TITLE
An Entity type entity.relics.spore has thrown an exception trying to write state. 

### ISSUE THREAD

**Issue by Yamijiro** [SSKirillSS/relics#184]
net.minecraft.ReportedException: Saving entity NBT
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.Entity.saveWithoutId(Entity.java:1744) ~[server-1.21.1-20240808.144430-srg.jar%23462!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.Entity.saveAsPassenger(Entity.java:1651) ~[server-1.21.1-20240808.144430-srg.jar%23462!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.Entity.save(Entity.java:1658) ~[server-1.21.1-20240808.144430-srg.jar%23462!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.chunk.storage.EntityStorage.lambda$storeEntities$1(EntityStorage.java:98) ~[server-1.21.1-20240808.144430-srg.jar%23462!/:?] {re:classloading}
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708) ~[?:?] {}
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?] {}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.chunk.storage.EntityStorage.storeEntities(EntityStorage.java:95) ~[server-1.21.1-20240808.144430-srg.jar%23462!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.entity.PersistentEntitySectionManager.storeChunkSections(PersistentEntitySectionManager.java:208) ~[server-1.21.1-20240808.144430-srg.jar%23462!/:?] {re:classloading,pl:accesstransformer:B}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.entity.PersistentEntitySectionManager.lambda$autoSave$13(PersistentEntitySectionManager.java:277) ~[server-1.21.1-20240808.144430-srg.jar%23462!/:?] {re:classloading,pl:accesstransformer:B}
        at MC-BOOTSTRAP/it.unimi.dsi.fastutil@8.5.12/it.unimi.dsi.fastutil.longs.LongOpenHashSet.forEach(LongOpenHashSet.java:762) ~[fastutil-8.5.12.jar%23113!/:?] {re:mixin}
        at MC-BOOTSTRAP/it.unimi.dsi.fastutil@8.5.12/it.unimi.dsi.fastutil.longs.LongIterable.forEach(LongIterable.java:146) ~[fastutil-8.5.12.jar%23113!/:?] {re:computing_frames,re:mixin}
        at MC-BOOTSTRAP/it.unimi.dsi.fastutil@8.5.12/it.unimi.dsi.fastutil.longs.AbstractLongCollection.forEach(AbstractLongCollection.java:153) ~[fastutil-8.5.12.jar%23113!/:?] {re:computing_frames,re:mixin}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.entity.PersistentEntitySectionManager.autoSave(PersistentEntitySectionManager.java:272) ~[server-1.21.1-20240808.144430-srg.jar%23462!/:?] {re:classloading,pl:accesstransformer:B}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerLevel.save(ServerLevel.java:823) ~[server-1.21.1-20240808.144430-srg.jar%23462!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin from mod cupboard,pl:mixin:APP:betterendisland.mixins.json:ServerLevelMixin from mod betterendisland,pl:mixin:APP:servercore.common.mixins.json:optimizations.ticking.chunk.random.ServerLevelMixin from mod servercore,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin from mod modernfix,pl:mixin:APP:eternal_starlight-common.mixins.json:ServerLevelMixin from mod eternal_starlight,pl:mixin:APP:servercore.common.mixins.json:features.activation_range.ServerLevelMixin from mod servercore,pl:mixin:APP:servercore.common.mixins.json:optimizations.sync_loads.ServerLevelMixin from mod servercore,pl:mixin:APP:the_bumblezone-common.mixins.json:world.ServerWorldMixin from mod the_bumblezone,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin from mod immersiveengineering,pl:mixin:APP:ohthetreesyoullgrow.mixins.json:MixinServerLevel from mod ohthetreesyoullgrow,pl:mixin:APP:corgilib-common.mixins.json:MixinServerLevel from mod corgilib,pl:mixin:APP:polymorph.mixins.json:MixinServerLevel from mod polymorph,pl:mixin:APP:hyperbox.mixins.json:ServerLevelMixin from mod hyperbox,pl:mixin:APP:refurbished_furniture.common.mixins.json:ServerLevelMixin from mod refurbished_furniture,pl:mixin:APP:observable.common.json:ServerLevelMixin from mod observable,pl:mixin:APP:kubejs.mixins.json:ServerLevelMixin from mod kubejs,pl:mixin:APP:comforts.mixins.json:MixinServerSleepStatus from mod comforts,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin from mod betterdeserttemples,pl:mixin:APP:ars_elemental.mixins.json:ServerLevelMixin from mod ars_elemental,pl:mixin:APP:betterendisland.mixins.json:EndergeticExpansionMixins from mod betterendisland,pl:mixin:A}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.saveAllChunks(MinecraftServer.java:551) ~[server-1.21.1-20240808.144430-srg.jar%23462!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.saveEverything(MinecraftServer.java:576) ~[server-1.21.1-20240808.144430-srg.jar%23462!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:929) ~[server-1.21.1-20240808.144430-srg.jar%23462!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:707) ~[server-1.21.1-20240808.144430-srg.jar%23462!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[server-1.21.1-20240808.144430-srg.jar%23462!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?] {re:mixin}
Caused by: java.lang.IllegalStateException: Cannot encode empty ItemStack
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.item.ItemStack.save(ItemStack.java:400) ~[server-1.21.1-20240808.144430-srg.jar%23462!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:apothic_enchanting.mixins.json:ItemStackMixin from mod apothic_enchanting,pl:mixin:APP:showcaseitem.mixins.json:ItemStackMixin from mod showcaseitem,pl:mixin:APP:placebo.mixins.json:ItemStackMixin from mod placebo,pl:mixin:APP:deeperdarker.mixins.json:ItemStackMixin from mod deeperdarker,pl:mixin:APP:kubejs.mixins.json:ItemStackMixin from mod kubejs,pl:mixin:APP:cucumber.mixins.json:ItemStackMixin from mod cucumber,pl:mixin:APP:mixins.artifacts.common.json:item.ItemStackMixin from mod artifacts,pl:mixin:APP:modern_industrialization.mixins.json:ItemStackMixin from mod modern_industrialization,pl:mixin:APP:tesseract_api.mixins.json:DataComponentTooltipProviderMixin from mod tesseract_api,pl:mixin:APP:tesseract_api.mixins.json:ItemStackExtraAttributeTooltipsMixin from mod tesseract_api,pl:mixin:APP:tesseract_api.mixins.json:event.ItemHurtEventMixin from mod tesseract_api,pl:mixin:APP:irons_spellbooks.mixins.json:ItemStackMixin from mod irons_spellbooks,pl:mixin:A}
        at TRANSFORMER/relics@0.9.2.0/it.hurts.sskirillss.relics.entities.SporeEntity.addAdditionalSaveData(SporeEntity.java:214) ~[relics-1.21-0.9.2.0.jar%23728!/:1.21-0.9.2.0] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.Entity.saveWithoutId(Entity.java:1723) ~[server-1.21.1-20240808.144430-srg.jar%23462!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        ... 19 more

**Comment by SSKirillSS** [comment]
Should not be an issue anymore due to the latest rework of Spore Sack.
