### ISSUE TITLE
StackOverflow in case of fixed randomness

### ISSUE THREAD

**Issue by TheDeadSnake** [SSKirillSS/relics#193]
# Method that causes the Overflow:
The recursive method `utils/MathUtils.multicast` has no upper limit / definite stopping point:
https://github.com/Octo-Studios/relics/blob/fffaec55b20ef1408630d811692472f0fd307daa/src/main/java/it/hurts/sskirillss/relics/utils/MathUtils.java#L42-L44

---
# How to reproduce:

Example Mod: Mahou Tsukai ([Link](https://www.curseforge.com/minecraft/mc-mods/mahou-tsukai))
1. Use Mahou Tsukais 'Rule Breaker' item, to fix randomness to a constant value
2. Kill a Mob

```
java.lang.StackOverflowError: Exception in server tick loop
	at TRANSFORMER/relics@0.9.2.0/it.hurts.sskirillss.relics.utils.MathUtils.multicast(MathUtils.java:43) ~[relics-1.21-0.9.2.0.jar%23845!/:1.21-0.9.2.0] {re:mixin,re:classloading}
	at TRANSFORMER/relics@0.9.2.0/it.hurts.sskirillss.relics.utils.MathUtils.multicast(MathUtils.java:43) ~[relics-1.21-0.9.2.0.jar%23845!/:1.21-0.9.2.0] {re:mixin,re:classloading}
[...]
```

**Comment by SSKirillSS** [comment]
Thanks for the info. Fixed in https://github.com/Octo-Studios/relics/commit/fb2981fdf24f4c906beca6d5134e2482ff32867f. Will be released in the next update.
