### ISSUE TITLE
Ghost skin talisman registry crash

### ISSUE THREAD

**Issue by sosqishy** [SSKirillSS/relics#53]
Hi! 

PREFACE: This issue is present without wearing, using or (at the time) even knowing about the Ghost Skin Talisman...

I'm playing the relics mod in a mod pack and have run into an issue that crashed the game. When you get shot by a skeleton before the arrow lands the game suddenly crashes. This happens after being shot with armor and without armor. It also happens with your inventory completely clear. We have uninstalled and reinstalled with no change. Any ideas? I have included the mods were using and the crash log separated by dashes. 

Thanks a lot!

@sosqishy
-------------------------------------------------------------------------------------------
MODS:

Curios API (Forge)
TheIllusiveC4
curios-forge-1.16.5-4.0.6.7.jar

Relics
SSKirillSS
relics-0.3.4.jar

Biomes O' Plenty
Forstride
BiomesOPlenty-1.16.5-13.1.0.477-universal.jar

Blueprint
TeamAbnormals
abnormals_core-1.16.5-3.3.0.jar

Charms
YaBoiChips_
charms-1.0.jar

Collective (Forge)
Serilum
collective-1.16.5-3.8.jar

Crowns Mod
djofox
Crowns1.16.4-1.16.5 v0.0.5.jar

Dragon Mounts: Legacy
WolfSh0tz
[1.16.X-1.0.10] Dragon Mounts Legacy.jar

Dummy Players
tterrag1098
DummyPlayers-1.0.1-release+4.jar

Emotecraft (Forge)
KosmX
emotecraft-for-MC1.16.5-2.0.9-forge.jar

Enhanced Mushrooms (Forge)
team_aurora_modding
Enhanced-Mushrooms-1.16.5-3.0.9.jar

Gems and Crystals Mod
Coliwogg
Gems-and-Crystals-1.16.5-1.3.2.jar

Goblin Traders
MrCrayfish
goblintraders-1.6.0-1.16.3.jar

Healing Campfire (Forge)
Serilum
healingcampfire_1.16.5-3.3.jar

Hwyla
TehNut
Hwyla-forge-1.10.11-B78_1.16.2.jar

Just Mob Heads (Forge)
Serilum
justmobheads_1.16.5-5.2.jar

Just Player Heads (Forge)
Serilum
justplayerheads_1.16.5-1.7.jar

Magic Combat Wands
dmitrylovin
magiccombatwands-forge-1.16-1.0.0.jar

Mermaid Tail Mod
ThatPreston
mermaidtail-1.4b.jar

Mountables
lukegrahamlandry
mountables-1.25.jar

MrCrayfish's Furniture Mod
MrCrayfish
cfm-7.0.0pre22-1.16.3.jar

Nature's Compass
Chaosyr
NaturesCompass-1.16.5-1.9.1-forge.jar

Repurposed Structures (Forge)
telepathicgrunt
repurposed_structures_forge-3.4.7+1.16.5.jar

Selene Lib
MehVahdJukaar
selene-1.16.5-1.9.0.jar

Simple Shops
wolforce
simpleshops-1.1.1.jar

Skin Layers 3D (Fabric/Forge)
tr9zw
3dSkinLayers-forge-1.1.0.jar

Sophisticated Backpacks
P3pp3rF1y
sophisticatedbackpacks-1.16.5-3.15.0.493.jar

Supplementaries
MehVahdJukaar
supplementaries-1.16.5-0.18.0.jar

Tree Harvester (Forge)
Serilum
treeharvester_1.16.5-4.1.jar

Wings
pau101
wings-2.0.1-1.16.5.jar

---------------------------------------------------------------------------------------------

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 1/6/22 12:14 AM
Description: Ticking entity

java.lang.NullPointerException: Registry Object not present: relics:ghost_skin_talisman
	at java.util.Objects.requireNonNull(Objects.java:290) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.RegistryObject.get(RegistryObject.java:120) ~[?:?] {re:mixin,re:classloading}
	at it.hurts.sskirillss.relics.items.relics.talisman.GhostSkinTalismanItem$Events.onProjectileImpact(GhostSkinTalismanItem.java:78) ~[?:0.3.4] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_131_Events_onProjectileImpact_ProjectileImpactEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3268/967596601.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onProjectileImpact(ForgeEventFactory.java:653) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.entity.projectile.AbstractArrowEntity.func_70071_h_(AbstractArrowEntity.java:187) ~[?:?] {re:computing_frames,re:classloading}
	at net.minecraft.entity.projectile.ArrowEntity.func_70071_h_(SourceFile:103) ~[?:?] {re:classloading}
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:252) ~[?:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:abnormals_core.mixins.json:client.ClientWorldMixin,pl:mixin:A}
	at net.minecraft.client.world.ClientWorld$$Lambda$7667/947533039.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:210) ~[?:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:abnormals_core.mixins.json:client.ClientWorldMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1485) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:954) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.22.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$467/210278405.call(Unknown Source) [forge-1.16.5-36.2.22.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.Objects.requireNonNull(Objects.java:290) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.RegistryObject.get(RegistryObject.java:120) ~[?:?] {re:mixin,re:classloading}
	at it.hurts.sskirillss.relics.items.relics.talisman.GhostSkinTalismanItem$Events.onProjectileImpact(GhostSkinTalismanItem.java:78) ~[?:0.3.4] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_131_Events_onProjectileImpact_ProjectileImpactEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3268/967596601.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onProjectileImpact(ForgeEventFactory.java:653) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.entity.projectile.AbstractArrowEntity.func_70071_h_(AbstractArrowEntity.java:187) ~[?:?] {re:computing_frames,re:classloading}
	at net.minecraft.entity.projectile.ArrowEntity.func_70071_h_(SourceFile:103) ~[?:?] {re:classloading}
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:252) ~[?:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:abnormals_core.mixins.json:client.ClientWorldMixin,pl:mixin:A}
	at net.minecraft.client.world.ClientWorld$$Lambda$7667/947533039.accept(Unknown Source) ~[?:?] {}
-- Entity being ticked --
Details:
	Entity Type: minecraft:arrow (net.minecraft.entity.projectile.ArrowEntity)
	Entity ID: 148376
	Entity Name: Arrow
	Entity's Exact location: 3938.19, 80.19, -1671.09
	Entity's Block location: World: (3938,80,-1672), Chunk: (at 2,5,8 in 246,-105; contains blocks 3936,0,-1680 to 3951,255,-1665), Region: (7,-4; contains chunks 224,-128 to 255,-97, blocks 3584,0,-2048 to 4095,255,-1537)
	Entity's Momentum: 0.97, -0.97, 0.85
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:210) ~[?:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:abnormals_core.mixins.json:client.ClientWorldMixin,pl:mixin:A}

-- Affected level --
Details:
	All players: 2 total; [ClientPlayerEntity['Mis_Xodiac'/148046, l='ClientLevel', x=3939.13, y=78.50, z=-1670.34], RemoteClientPlayerEntity['loki_on_fire'/80479, l='ClientLevel', x=3943.50, y=85.06, z=-1769.50]]
	Chunk stats: Client Chunk Cache: 729, 504
	Level dimension: minecraft:overworld
	Level spawn location: World: (506,133,198), Chunk: (at 10,8,6 in 31,12; contains blocks 496,0,192 to 511,255,207), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 10989878 game time, 1950101 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:abnormals_core.mixins.json:client.ClientWorldMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2031) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.22.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$467/210278405.call(Unknown Source) [forge-1.16.5-36.2.22.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 871972440 bytes (831 MB) / 2105016320 bytes (2007 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 8
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.22.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.22.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.22.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.22.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G8%20(2).jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.22.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.22
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.22-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		repurposed_structures_forge-3.4.7+1.16.5.jar      |Repurposed Structures         |repurposed_structures         |3.4.7+1.16.5        |DONE      |Manifest: NOSIGNATURE
		magiccombatwands-forge-1.16-1.0.0.jar             |Magic Combat Wands            |magiccombatwands              |1.0.0               |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.16.5-13.1.0.477-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.5-13.1.0.477   |DONE      |Manifest: NOSIGNATURE
		simpleshops-1.1.1.jar                             |Simple Shops                  |simpleshops                   |1.1.1               |DONE      |Manifest: NOSIGNATURE
		treeharvester_1.16.5-4.1.jar                      |Tree Harvester                |treeharvester                 |4.1                 |DONE      |Manifest: NOSIGNATURE
		abnormals_core-1.16.5-3.3.0.jar                   |Abnormals Core                |abnormals_core                |3.3.0               |DONE      |Manifest: NOSIGNATURE
		Enhanced-Mushrooms-1.16.5-3.0.9.jar               |Enhanced Mushrooms            |enhanced_mushrooms            |1.16.5-3.0.9        |DONE      |Manifest: NOSIGNATURE
		justmobheads_1.16.5-5.2.jar                       |Just Mob Heads                |justmobheads                  |5.2                 |DONE      |Manifest: NOSIGNATURE
		goblintraders-1.6.0-1.16.3.jar                    |Goblin Traders                |goblintraders                 |1.6.0               |DONE      |Manifest: NOSIGNATURE
		justplayerheads_1.16.5-1.7.jar                    |Just Player Heads             |justplayerheads               |1.7                 |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.0.6.8.jar                   |Curios API                    |curios                        |1.16.5-4.0.6.8      |DONE      |Manifest: NOSIGNATURE
		mermaidtail-1.4b.jar                              |Mermaid Tail Mod              |mermaidtail                   |1.16.4-1.4.0        |DONE      |Manifest: NOSIGNATURE
		collective-1.16.5-3.8.jar                         |Collective                    |collective                    |3.8                 |DONE      |Manifest: NOSIGNATURE
		NaturesCompass-1.16.5-1.9.1-forge.jar             |Nature's Compass              |naturescompass                |1.16.5-1.9.1-forge  |DONE      |Manifest: NOSIGNATURE
		mountables-1.25.jar                               |Mountables                    |mountables                    |1.25                |DONE      |Manifest: NOSIGNATURE
		DummyPlayers-1.0.1-release+4.jar                  |DummyPlayers                  |dummyplayers                  |1.0.1-release+4     |DONE      |Manifest: NOSIGNATURE
		Gems-and-Crystals-1.16.5-1.3.2.jar                |Gems and Crystals             |gemsandcrystals               |1.16.5-1.3.2        |DONE      |Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.16.5-3.15.0.493.jar      |Sophisticated Backpacks       |sophisticatedbackpacks        |1.16.5-3.15.0.493   |DONE      |Manifest: NOSIGNATURE
		relics-0.3.4.jar                                  |Relics                        |relics                        |0.3.4               |DONE      |Manifest: NOSIGNATURE
		charms-1.0.jar                                    |Charms                        |charms                        |1.0                 |DONE      |Manifest: NOSIGNATURE
		cfm-7.0.0pre22-1.16.3.jar                         |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre22         |DONE      |Manifest: NOSIGNATURE
		Hwyla-forge-1.10.11-B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  |DONE      |Manifest: NOSIGNATURE
		3dSkinLayers-forge-1.1.0.jar                      |3dSkinLayers                  |skinlayers3d                  |1.1.0               |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.22-universal.jar                |Forge                         |forge                         |36.2.22             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		wings-2.0.1-1.16.5.jar                            |Wings                         |wings                         |2.0.1               |DONE      |Manifest: NOSIGNATURE
		Crowns1.16.4-1.16.5 v0.0.5.jar                    |Crowns Mod                    |crowns                        |0.0.5               |DONE      |Manifest: NOSIGNATURE
		[1.16.X-1.0.10] Dragon Mounts Legacy.jar          |Dragon Mounts: Legacy         |dragonmounts                  |1.0.10              |DONE      |Manifest: NOSIGNATURE
		supplementaries-1.16.5-0.18.0.jar                 |Supplementaries               |supplementaries               |0.18.0              |DONE      |Manifest: NOSIGNATURE
		healingcampfire_1.16.5-3.3.jar                    |Healing Campfire              |healingcampfire               |3.3                 |DONE      |Manifest: NOSIGNATURE
		emotecraft-for-MC1.16.5-2.0.9-forge.jar           |Emotecraft                    |emotecraft                    |2.0.9               |DONE      |Manifest: NOSIGNATURE
		selene-1.16.5-1.9.0.jar                           |Selene                        |selene                        |1.16.5-1.0          |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 1ba0fd02-a185-438a-ad0d-19dd8a77bcb2
	Launched Version: forge-36.2.22
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) UHD Graphics GL version 4.6.0 - Build 27.20.100.9365, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, mod_resources
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz
	OptiFine Version: OptiFine_1.16.5_HD_U_G8
	OptiFine Build: 20210515-161946
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 27.20.100.9365
	OpenGlRenderer: Intel(R) UHD Graphics
	OpenGlVendor: Intel
	CpuCount: 8

**Comment by SSKirillSS** [comment]
1. Make sure you have only one version of Relics installed
2. If you're playing on server, make sure that Relics version are the same both on server and client

**Comment by SSKirillSS** [comment]
Closed. If you still have this issue - reopen the ticket.
